periodics:
- cron: '0 7 * * *'
  agent: kubernetes
  name: elfs-daily-e2e-lssd
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh elfs-daily-e2e-lssd lssd 30'

- cron: '0 7 * * *'
  agent: kubernetes
  name: elfs-daily-e2e-pssd
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh elfs-daily-e2e-pssd pssd 30'

- cron: '0 7 * * *'
  agent: kubernetes
  name: elfs-daily-e2e-phdd
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh elfs-daily-e2e-phdd phdd 30'


- cron: '0 14,22 * * *'
  agent: kubernetes
  name: elfs-daily-io-lssd
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh  elfs-daily-io-lssd lssd  300'

- cron: '0 14,22 * * *'
  agent: kubernetes
  name: elfs-daily-io-pssd
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh  elfs-daily-io-pssd pssd 300'

- cron: '0 14,22 * * *'
  agent: kubernetes
  name: elfs-daily-io-phdd
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh  elfs-daily-io-phdd phdd 300'


- cron: '0 8 * * *'
  agent: kubernetes
  name: elfs-perf-lssd
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh  elfs-perf-lssd lssd  600'

- cron: '0 8 * * *'
  agent: kubernetes
  name: elfs-perf-pssd
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh  elfs-perf-pssd  pssd  600'

- cron: '0 8 * * *'
  agent: kubernetes
  name: elfs-perf-phdd
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh  elfs-perf-phdd phdd  600'

- cron: '0 10 * * *'
  agent: kubernetes
  name: elfs-scalability-lssd
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh  elfs-scalability-lssd lssd 600'


- cron: '0 10  * * *'
  agent: kubernetes
  name: elfs-scalability-pssd
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh  elfs-scalability-pssd pssd 600'

- cron: '0 10 * * *'
  agent: kubernetes
  name: elfs-scalability-phdd
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh elfs-scalability-phdd phdd  600'


- cron: '0 9 * * *'
  agent: kubernetes
  name: elfs-ha-lssd-node
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh elfs-ha-lssd-node lssd 600'

- cron: '0 9 * * *'
  agent: kubernetes
  name: elfs-ha-pssd-node
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh elfs-ha-pssd-node pssd 600'

- cron: '0 9 * * *'
  agent: kubernetes
  name: elfs-ha-phdd-node
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh elfs-ha-phdd-node phdd  600'


- cron: '0 0 1 1 *'
  agent: kubernetes
  name: elfs-ha-lssd-disk
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh elfs-ha-lssd-disk lssd 60'

- cron: '0 9 * * *'
  agent: kubernetes
  name: elfs-ha-pssd-disk
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh elfs-ha-pssd-disk pssd 60'

- cron: '0 9 * * *'
  agent: kubernetes
  name: elfs-ha-phdd-disk
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh elfs-ha-phdd-disk phdd  60'



- cron: '0 5 * * 1'
  agent: kubernetes
  name: elfs-cleanup
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh elfs-cleanup'


- cron: '0 11 * * *'
  agent: kubernetes
  name: elfs-demo-lssd-single
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh  elfs-demo-lssd-single lssd  600'

- cron: '0 11 * * *'
  agent: kubernetes
  name:  elfs-demo-pssd-single
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh elfs-demo-pssd-single pssd  600'

- cron: '0 11 * * *'
  agent: kubernetes
  name: elfs-demo-phdd-single
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh elfs-demo-phdd-single phdd  600'

- cron: '0 13 * * *'
  agent: kubernetes
  name: elfs-demo-lssd-scalability
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh elfs-demo-lssd-scalability lssd  600'

- cron: '0 13 * * *'
  agent: kubernetes
  name:  elfs-demo-pssd-scalability
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh elfs-demo-pssd-scalability pssd  600'

- cron: '0 13 * * *'
  agent: kubernetes
  name: elfs-demo-phdd-scalability
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh elfs-demo-phdd-scalability phdd  600'


postsubmits:
  minzhuogoogle/storage-performance:
  - name: elfs-ps-lssd
    max_concurrency: 1
    agent: kubernetes
    spec:
      containers:
      - image: gcr.io/cpe-performance-storage/elastifile:latest
        tty: true
        stdin: true
        command:
        - /bin/bash
        - -c
        args:
        - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh elfs-ps-pssd lssd 30'

  - name: elfs-ps-pssd
    max_concurrency: 1
    agent: kubernetes
    spec:
      containers:
      - image: gcr.io/cpe-performance-storage/elastifile:latest
        tty: true
        stdin: true
        command:
        - /bin/bash
        - -c
        args:
        - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh elfs-ps-pssd pssd 30'

  - name: elfs-ps-phdd
    max_concurrency: 1
    agent: kubernetes
    spec:
      containers:
      - image: gcr.io/cpe-performance-storage/elastifile:latest
        tty: true
        stdin: true
        command:
        - /bin/bash
        - -c
        args:
        - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh elfs-ps-phdd phdd 30'
