periodics:
- interval: 90m
  agent: kubernetes
  name: elastifile-daily-e2e-local-ssd
  max_concurrency: 1
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh lssd 0'


- interval: 4h
  agent: kubernetes
  name: elastifile-daily-e2e-pssd
  max_concurrency: 1
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh pssd 0 0'

- interval: 4h
  agent: kubernetes
  name: elastifile-daily-e2e-phdd
  max_concurrency: 1
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh phdd 0 0'


postsubmits:
  minzhuogoogle/storage-performance:
  - name: elfs-postsubmit-local-ssd
    max_concurrency: 1
    agent: kubernetes
    spec:
      containers:
      - image: gcr.io/cpe-performance-storage/elastifile:latest
        tty: true
        stdin: true
        command:
        - /bin/bash
        - -c
        args:
        - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh lssd 1 1'

  - name: elfs-postsubmit-pssd
    max_concurrency: 0
    agent: kubernetes
    spec:
      containers:
      - image: gcr.io/cpe-performance-storage/elastifile:latest
        tty: true
        stdin: true
        command:
        - /bin/bash
        - -c
        args:
        - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh pssd  1 1'


  - name: elfs-postsubmit-phdd
    max_concurrency: 1
    agent: kubernetes
    spec:
      containers:
      - image: gcr.io/cpe-performance-storage/elastifile:latest
        tty: true
        stdin: true
        command:
        - /bin/bash
        - -c
        args:
        - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh phdd 1 1'

