periodics:
- cron: '0 7 * * *'
  agent: kubernetes
  name: daily-e2e-lssd
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh lssd 300 elfs-daily-e2e-lssd'

- cron: '0 7 * * *'
  agent: kubernetes
  name: elfs-daily-e2e-pssd
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh pssd 300 elfs-daily-e2e-pssd'

- cron: '0 7 * * *'
  agent: kubernetes
  name: daily-e2e-phdd
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh phdd  300 elfs-daily-e2e-phdd'


- cron: '0 12,17,22,3 * * 1,2,3,4,5,6'
  agent: kubernete
  name: elfs-daily-io-lssd
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh lssd  300 elfs-daily-io-lssd'

- cron: '0 12,17,22,3 * * 1,2,3,4,5,6'
  agent: kubernetes
  name: elfs-daily-io-pssd
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh pssd 300 elfs-daily-io-pssd'

- cron: '0 12,17,22,3 * * 1,2,3,4,5,6'
  agent: kubernetes
  name: elfs-daily-io-phdd
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh phdd 300 elfs-daily-io-phdd'


- cron: '0 9 * * 0'
  agent: kubernetes
  name: elfs-perf-lssd
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh lssd  600 elfs-perf-lssd'

- cron: '0 9 * * 0'
  agent: kubernetes
  name: elfs-perf-pssd
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh pssd  600 elfs-perf-pssd'

- cron: '0 9 * * 0'
  agent: kubernetes
  name: elfs-perf-phdd
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh phdd  600 elfs-perf-phdd'

- cron: '0 11 * * 0'
  agent: kubernetes
  name: elfs-scalability-lssd
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh lssd 600 elfs-scalability-lssd'


- cron: '0 11  * * 0'
  agent: kubernetes
  name: elfs-scalability-pssd
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh pssd 600 elfs-scalability-pssd'

- cron: '0 11 * * 0'
  agent: kubernetes
  name: elfs-scalability-phdd
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh phdd  600 elfs-scalability-phdd'


- cron: '0 15 * * 0'
  agent: kubernetes
  name: elfs-ha-lssd-node
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh lssd 60 elfs-ha-lssd-node'

- cron: '0 15 * * 0'
  agent: kubernetes
  name: elfs-ha-pssd-node
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh pssd 60 elfs-ha-pssd-node'

- cron: '0 15 * * 0'
  agent: kubernetes
  name: elfs-ha-phdd-node
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh phdd  60 elfs-ha-phdd-node'


- cron: '0 18 * * 0'
  agent: kubernetes
  name: elfs-ha-lssd-disk
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh lssd 60 elfs-ha-lssd-disk'

- cron: '0 18 * * 0'
  agent: kubernetes
  name: elfs-ha-pssd-disk
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh pssd 60 elfs-ha-pssd-disk'

- cron: '0 18 * * 0'
  agent: kubernetes
  name: elfs-ha-phdd-disk
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh phdd  60 elfs-ha-phdd-disk'



- cron: '0 5 * * 0'
  agent: kubernetes
  name: elfs-cleanup
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh elfs-cleanup'


- cron: '0 3 * * 0'
  agent: kubernetes
  name: elfs-demo-lssd-scale
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh lssd  600 elfs-demo-lssd-scale'

- cron: '0 3 * * 0'
  agent: kubernetes
  name:  elfs-demo-pssd-scale
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh pssd  600  elfs-demo-pssd-scale'

- cron: '0 3 * * 0'
  agent: kubernetes
  name: elfs-demo-phdd-scale
  spec:
    containers:
    - image: gcr.io/cpe-performance-storage/elastifile:latest
      tty: true
      stdin: true
      command:
      - /bin/bash
      - -c
      args:
      - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh phdd  600 elfs-demo-phdd-scale'



postsubmits:
  minzhuogoogle/storage-performance:
  - name: elfs-ps-lssd
    max_concurrency: 1
    agent: kubernetes
    spec:
      containers:
      - image: gcr.io/cpe-performance-storage/elastifile:latest
        tty: true
        stdin: true
        command:
        - /bin/bash
        - -c
        args:
        - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh lssd 120 elfs-ps-lssd'


  - name: elfs-ps-pssd
    max_concurrency: 1
    agent: kubernetes
    spec:
      containers:
      - image: gcr.io/cpe-performance-storage/elastifile:latest
        tty: true
        stdin: true
        command:
        - /bin/bash
        - -c
        args:
        - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh pssd 120 elfs-ps-pssd'


  - name: elfs-ps-phdd
    max_concurrency: 0
    agent: kubernetes
    spec:
      containers:
      - image: gcr.io/cpe-performance-storage/elastifile:latest
        tty: true
        stdin: true
        command:
        - /bin/bash
        - -c
        args:
        - 'curl -OL https://raw.githubusercontent.com/minzhuogoogle/cpe-test/master/scripts/shell/elfse2e.sh; chmod 777 elfse2e.sh; ./elfse2e.sh phdd 120 elfs-ps-phdd'
